import { createFileRoute, Link } from "@tanstack/react-router";
import { motion } from "framer-motion";
import { Sparkles, TrendingDown, ArrowRight, Twitter, Linkedin } from "lucide-react";
import { Button } from "@/components/ui/button";
import { AuroraBackground } from "@/components/site/Background";
import { AnimatedCounter } from "@/components/site/AnimatedCounter";

export const Route = createFileRoute("/report")({
  head: () => ({
    meta: [
      { title: "Acme Inc saved $1,840/mo on AI tools — SpendPilot" },
      { name: "description", content: "See how this team cut their AI subscription costs by 38%." },
      { property: "og:title", content: "Acme Inc saved $1,840/mo with SpendPilot" },
      { property: "og:description", content: "Public AI spend audit report — 38% reduction in monthly costs." },
      { property: "og:type", content: "article" },
    ],
  }),
  component: PublicReport,
});

function PublicReport() {
  const tools = [
    { name: "OpenAI API", saving: 1100 },
    { name: "Cursor Pro", saving: 80 },
    { name: "ChatGPT Team", saving: 120 },
    { name: "Claude Pro", saving: 120 },
  ];

  return (
    <div className="relative min-h-screen">
      <AuroraBackground />
      <header className="px-6 py-6 flex items-center justify-between max-w-6xl mx-auto">
        <Link to="/" className="flex items-center gap-2">
          <div className="h-8 w-8 rounded-lg bg-linear-to-br from-electric to-violet grid place-items-center">
            <Sparkles className="h-4 w-4 text-white" />
          </div>
          <span className="font-display font-semibold">Spend<span className="gradient-text">Pilot</span></span>
        </Link>
        <Button asChild variant="hero" size="sm">
          <Link to="/audit">Run my audit</Link>
        </Button>
      </header>

      <main className="px-6 py-12">
        <div className="mx-auto max-w-3xl">
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            className="text-center"
          >
            <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full glass text-xs">
              <span className="h-1.5 w-1.5 rounded-full bg-success animate-pulse" />
              Verified savings report
            </div>
            <h1 className="mt-6 text-4xl md:text-6xl font-bold tracking-tight">
              Acme Inc cut their AI bill by <span className="gradient-text">38%</span>
            </h1>
            <p className="mt-4 text-muted-foreground max-w-xl mx-auto">
              An 8-person engineering team's audit results, generated by SpendPilot.
            </p>
          </motion.div>

          <motion.div
            initial={{ opacity: 0, scale: 0.95 }}
            animate={{ opacity: 1, scale: 1 }}
            transition={{ delay: 0.15 }}
            className="mt-10 relative"
          >
            <div className="absolute -inset-6 bg-linear-to-r from-(--electric)/30 to-(--violet)/30 blur-3xl rounded-3xl" />
            <div className="relative glass-strong rounded-3xl p-10 text-center gradient-border">
              <div className="text-xs uppercase tracking-wider text-muted-foreground">Monthly savings</div>
              <div className="mt-2 text-7xl md:text-8xl font-bold gradient-text">
                $<AnimatedCounter value={1840} />
              </div>
              <div className="mt-3 inline-flex items-center gap-2 text-success text-sm">
                <TrendingDown className="h-4 w-4" /> $22,080 saved per year
              </div>
            </div>
          </motion.div>

          <div className="mt-10 grid sm:grid-cols-2 gap-3">
            {tools.map((t, i) => (
              <motion.div
                key={t.name}
                initial={{ opacity: 0, y: 20 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ delay: 0.2 + i * 0.06 }}
                className="glass-strong rounded-2xl p-5 flex items-center justify-between"
              >
                <span className="font-medium">{t.name}</span>
                <span className="text-success font-bold">-${t.saving}/mo</span>
              </motion.div>
            ))}
          </div>

          <div className="mt-12 glass-strong rounded-2xl p-8 text-center gradient-border">
            <h3 className="text-2xl font-bold">Find your savings</h3>
            <p className="mt-2 text-sm text-muted-foreground">Free, private, takes 2 minutes.</p>
            <div className="mt-6 flex flex-col sm:flex-row gap-3 justify-center">
              <Button asChild variant="hero" size="lg">
                <Link to="/audit">Start free audit <ArrowRight className="h-4 w-4" /></Link>
              </Button>
              <Button variant="glass" size="lg">
                <Twitter className="h-4 w-4" /> Share
              </Button>
              <Button variant="glass" size="lg">
                <Linkedin className="h-4 w-4" /> Share
              </Button>
            </div>
          </div>

          <div className="mt-10 text-center text-xs text-muted-foreground">
            Generated by <Link to="/" className="text-foreground hover:underline">SpendPilot</Link> · Public report
          </div>
        </div>
      </main>
    </div>
  );
}
